name: Build ModMenu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-lastest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: configure
      run: cmake -G "Visual Studio 17 2022" -B build -DCMAKE_BUILD_TYPE=Release -T host=x86 -A win32
    # build project
    - name: build
      run: cmake --build build --config Release --target ALL_BUILD
