name: Build ModMenu
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: Configure
      run: cmake -G "Visual Studio 16 2019" -B build -DCMAKE_BUILD_TYPE=Release -T host=x86 -A win32
    # build project
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD
