name: GDMM nightly auto build

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  Windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -T host=x86 -A win32

    - name: Build
      # Build your program with the given configuration
      run: cmake --build build --config Release --target ModMenu
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows Binary
        path: ./build/Release
